apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
data:
  JWT_SALT: "lUD9PRRjbdUzPEYc"
  JWT_EXPIRATION: "3600"
  DATABASE_URL: "postgres://authuser:authpass@postgres:5432/authdb"
  POSTGRES_DB: "authdb"
  POSTGRES_USER: "authuser"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secrets
type: Opaque
stringData:
  JWT_SECRET: "lUD9PRRjbdUzPEYc="
  POSTGRES_PASSWORD: "authpass" 