on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 1 | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-backend:latest .
          docker tag ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-backend:latest ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-backend:${{ github.sha }}

      - name: Push backend Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-backend:latest
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-backend:${{ github.sha }}

      - name: Build frontend Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-frontend:latest -f auth_api_frontend/Dockerfile ./auth_api_frontend
          docker tag ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-frontend:latest ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-frontend:${{ github.sha }}

      - name: Push frontend Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-frontend:latest
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}-frontend:${{ github.sha }}
